from typing import Optional

from sqlmodel import Field, SQLModel


class IngredientBase(SQLModel):
    """
    Base model containing common fields for Ingredient.
    This helps avoid code duplication across Create, Read, and Table models.
    """

    name: str = Field(
        index=True
    )  # index=True makes it faster to search by name
    category: str = Field(default="Condiment", index=True)
    quantity: int = Field(default=0)
    description: Optional[str] = None


class Ingredient(IngredientBase, table=True):
    """
    Database model for the 'ingredient' table.
    table=True tells SQLModel that this is a table definition, not just a Pydantic model.
    """

    id: Optional[int] = Field(default=None, primary_key=True)


class IngredientCreate(IngredientBase):
    """
    Model for creating a new Ingredient.
    It inherits fields from IngredientBase but doesn't include 'id'
    because the ID is generated by the database.
    """

    pass


class IngredientRead(IngredientBase):
    """
    Model for reading/returning Ingredient data.
    This includes the 'id' field which is available after creation.
    """

    id: int


class IngredientUpdate(SQLModel):
    """
    Model for updating an Ingredient.
    All fields are optional because a user might want to update just one field.
    We don't inherit from IngredientBase because those fields are required by default.
    """

    name: Optional[str] = None
    category: Optional[str] = None
    quantity: Optional[int] = None
    description: Optional[str] = None
